# Offense count: 29
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
AllCops:
  TargetRubyVersion: 2.7.3
  Exclude:
    - "*Brewfile"
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/GuardClause:
  Enabled: false

### Metrics
Metrics/BlockLength:
  Max: 50

Metrics/AbcSize:
  Max: 30
  Exclude:

Metrics/ClassLength:
  Max: 160
  Exclude:

Layout/LineLength:
  Max: 120

Metrics/ModuleLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
