
version: "3"
services:
  code-server:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    shm_size: '2gb'
    container_name: code-server
    environment:
      # Set CODE_SERVER_PASSWORD in your shell to change the default password
      PASSWORD: ${CODE_SERVER_PASSWORD:-changeme}
    ports:
      - 8080:8080
    volumes:
      - ~/.gitconfig:/home/coder/.gitconfig
      - ~/.ssh:/home/coder/.ssh
      - ../volume/extensions:/home/coder/.local/share/code-server/extensions
