
version: "3"
services:
  code-server:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    shm_size: '2gb'
    container_name: code-server
    environment:
      # SECURITY: Set CODE_SERVER_PASSWORD environment variable before starting
      # Example: export CODE_SERVER_PASSWORD="your-secure-password"
      # Do not use the default password 'changeme' in production
      PASSWORD: ${CODE_SERVER_PASSWORD:?CODE_SERVER_PASSWORD environment variable must be set}
    ports:
      - 8080:8080
    volumes:
      - ~/.gitconfig:/home/coder/.gitconfig
      # SECURITY: Mount SSH keys selectively instead of entire ~/.ssh directory
      # Uncomment and modify as needed:
      # - ~/.ssh/id_rsa.pub:/home/coder/.ssh/id_rsa.pub:ro
      # - ~/.ssh/config:/home/coder/.ssh/config:ro
      # Alternative: Use SSH agent forwarding instead of mounting keys
      - ../volume/extensions:/home/coder/.local/share/code-server/extensions
